set APPVEYOR_BUILD_NUMBER=100
set APPVEYOR_BUILD_VERSION=2.1.5.100
set UMBRACO_PACKAGE_MIN_VERSION=7.2.1
set UMBRACO_PACKAGE_PRERELEASE_SUFFIX=
REM ** Generally branch should be either master or Release **
set APPVEYOR_REPO_BRANCH=v2
build.bat