//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.2.93
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace TestSite.Logic.Models.DocumentTypes
{
	/// <summary>Archetype Test</summary>
	[PublishedContentModel("archetypeTestDoc")]
	public partial class ArchetypeTestDoc : UmbTextPage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "archetypeTestDoc";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ArchetypeTestDoc(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ArchetypeTestDoc, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Archetype Test
		///</summary>
		[ImplementPropertyType("archetypeTest")]
		public Archetype.Models.ArchetypeModel ArchetypeTest
		{
			get { return this.GetPropertyValue<Archetype.Models.ArchetypeModel>("archetypeTest"); }
		}
	}
}
